---
title: "Trending Youtube Dashboard Report"
output: 
  html_document:
  theme:
    bootswatch = "journal",
    base_font = bslib::font_google("Assistant"))
    sysfonts::font_add_google("Assistant")
    thematic_shiny(font = "auto")
    showtext::showtext_auto()
params:
  daterange: NA
  rm_outliers: NA
  boxplotdist: NA
  barplotcat: NA
  bubbleCats: NA
  num_tags: NA
  vid_category: NA
  representation_format: NA
---
  
```{r setup, include=FALSE}
# Loading in the data
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(shiny)
library(bslib)
library(shinyWidgets)
library(shinydashboard)
library(ggplot2)
library(forcats)
library(plotly)
library(thematic)
library(scales)
library(rlang)
library(stringr)
library(showtext)
library(sysfonts)
library(packcircles)
library(lubridate)
library(rsconnect)
library(rmarkdown)

data <- read.csv("data/processed/CA_youtube_trending_data_processed.csv")

# Filter data by date universally
data_by_date <- data |>
  dplyr::filter(trending_date > params$daterange[1] & trending_date < params$daterange[2])

# Filter out outliers if toggled
if (params$rm_outliers == TRUE) {
  data <- data_by_date |>
    dplyr::filter(!!rlang::sym(params$boxplotdist) < quantile(!!rlang::sym(params$boxplotdist), 0.9))
  boxplot_data <- data
} else {
  boxplot_data <- data_by_date
}

boxplot_options <- c(
  "Comments" = "comment_count",
  "Dislikes" = "dislikes",
  "Likes" = "likes",
  "Views" = "view_count"
)

interval_choices <- c("Day of Week" = "publish_wday",
                      "Month of Year" = "publish_month", 
                      "Time of Day" = "publish_hour")

barplot_colours <- setNames(
  unique(data$categoryId),
  c("#35618f", "#2dadb8", "#2a6a45", "#0df38f", "#93c680",
    "#21a708", "#bce333", "#7e2b19", "#de592e", "#fcd107",
    "#b08965", "#d4d4d4", "#5c51b1", "#cc99d9", "#a53bb7")
)

boxplot_colours <- setNames(
  c("#35618f", "#2dadb8", "#2a6a45", "#0df38f", "#93c680",
    "#21a708", "#bce333", "#7e2b19", "#de592e", "#fcd107",
    "#b08965", "#d4d4d4", "#5c51b1", "#cc99d9", "#a53bb7"),
  unique(data$categoryId)
)

```

```{r}
# Plots

# Video Counter
video_count_box <-
  shinydashboard::valueBox(
    span(icon("video"), length(unique(data_by_date$video_id))),
    subtitle = "Total Video Count"
  )
# video_count_box

# Channel Counter
channel_count_box <- shinydashboard::valueBox(span(icon("user"), length(unique(
  data_by_date$channelId
))),
subtitle = "Total Channel Count")

# channel_count_box

```

## Distribution Boxplots

**Use your cursor to select an area to zoom or hover to gain additional information**

```{r}
paste("Exclude Outliers (>0.9 Quantile):", params$rm_outliers)
paste("Distribution Metric:", params$boxplotdist)
```
  
```{r}
# Category Boxplot
box_plot <- boxplot_data |>
  dplyr::arrange(trending_date) |>
  dplyr::distinct(video_id, .keep_all = TRUE) |> # keep most recent data point for accurate tracking (no aggregating the same video)
  ggplot2::ggplot() +
  ggplot2::geom_boxplot(
    aes(
      x = forcats::fct_reorder(categoryId, !!rlang::sym(params$boxplotdist)),
      y = !!rlang::sym(params$boxplotdist),
      fill = categoryId
    )
  ) +
  ggplot2::labs(
    y = names(boxplot_options[which(boxplot_options == params$boxplotdist)]),
    x = 'Category',
  ) +
  ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = cut_short_scale()), breaks = scales::breaks_pretty(n = 5)) +
  ggplot2::scale_fill_manual(values = boxplot_colours) +
  ggplot2::guides(fill = FALSE) +
  ggplot2::theme(axis.title.x = element_text(size = 14, face = "bold"),
                 axis.title.y = element_text(size = 14, face = "bold")) +
  ggplot2::coord_flip()

# Display the plot
plotly::ggplotly(box_plot, tooltip = "text")

```

## Trending Videos by Channel

**Hover your cursor over the graph to gain additional information**

```{r}
paste("Category:", params$barplotcat)
```
  
```{r}
# Channel Barplot
bar_plot <- data_by_date |>
  dplyr::filter(categoryId == params$barplotcat) |>
  dplyr::group_by(channelId, channelTitle) |>
  dplyr::summarise(video_count = length(unique(video_id))) |>
  dplyr::arrange(dplyr::desc(video_count)) |>
  dplyr::ungroup() |>
  dplyr::slice(1:10) |>
  ggplot2::ggplot(aes(
    x = video_count,
    y = reorder(channelTitle, video_count),
    text = paste("Count: ", video_count)
  )) +
  ggplot2::geom_bar(stat = "identity",
                    fill = names(barplot_colours[which(barplot_colours == params$barplotcat)])) +
  ggplot2::labs(x = 'Count of Videos',
                y = 'Channel Name') +
  ggplot2::scale_y_discrete(
    labels = function(x) {
      stringr::str_wrap(x, width = 20)
    }
  ) +
  ggplot2::theme(
    axis.title.x = element_text(size = 14, face = "bold"),
    axis.title.y = element_text(size = 14, face = "bold")
  )


# Display the plot
plotly::ggplotly(bar_plot, tooltip = "text")

```

## Common Tags by Category

**Hover your cursor over the graph to gain additional information**

```{r}
paste("Number of Tags:", params$num_tags)
```

```{r}
# Bubble Tags Plot
bubble <-
  filtered_tag_counts <- data_by_date |>
  # Filter date and categories
  dplyr::filter(categoryId %in% params$bubbleCats) |>
  # Lowercase, count and sort remaining tags
  dplyr::mutate(tags = tolower(tags)) |>
  dplyr::pull(tags) |>
  stringr::str_split(fixed("|")) |>
  unlist() |>
  table(dnn = c("tag")) |>
  sort(decreasing = TRUE) |>
  as.data.frame() |>
  subset(tag != "[none]")

# Functions to "pack" the circles in a nice layout
packing <-
  packcircles::circleProgressiveLayout(filtered_tag_counts$Freq[1:params$num_tags])
packing$radius <- 0.95 * packing$radius
packing$counts <- filtered_tag_counts$Freq[1:params$num_tags]
bubbleplot_data <- packcircles::circleLayoutVertices(packing)
bubble_labels <-
  stringr::str_wrap(filtered_tag_counts$tag[1:params$num_tags], 10)

# Create the plot
bubble_plot <-
  ggplot2::ggplot(bubbleplot_data, aes(x, y, text = paste("Rank: ", id))) +
  ggplot2::geom_polygon(aes(group = id, fill = id),
                        colour = "black",
                        show.legend = FALSE) +
  ggplot2::geom_text(
    data = packing,
    aes(
      x,
      y,
      text = paste("Tag: ", filtered_tag_counts$tag[1:params$num_tags], "\nNumber of Videos: ", counts)
    ),
    label = bubble_labels,
    size = 3,
    color = "white"
  ) +
  ggplot2::scale_fill_viridis_c() +
  ggplot2::theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# Display the plot
plotly::ggplotly(bubble_plot, tooltip = "text")

```

## Popular Publishing Times

```{r}
paste("Representation Format:", params$representation_format)
paste("Category:", params$vid_category)
```

```{r}
# Polar Coordinates
polar_coor <-
  data_filtered <- data_by_date |>
  # Filtering dataset by category
  dplyr::filter(categoryId == params$vid_category) |>
  # Creating new columns for date components
  dplyr::mutate(publishedAt = lubridate::ymd_hms(publishedAt)) |>
  dplyr::mutate(
    publish_date = lubridate::date(publishedAt),
    publish_month = lubridate::month(publishedAt, label = TRUE),
    publish_wday = lubridate::wday(publishedAt, label = TRUE),
    publish_hour = lubridate::hour(publishedAt)
  ) |>
  dplyr::group_by(!!rlang::sym(params$representation_format)) |>
  dplyr::summarise(video_count = length(unique(video_id)))

# Render plot
ggplot2::ggplot(data_filtered,
                aes(x = .data[[params$representation_format]], y = video_count, fill = video_count)) +
  ggplot2::geom_bar(stat = "identity") +
  ggplot2::xlab(names(interval_choices[which(interval_choices == params$representation_format)])) +
  ggplot2::scale_fill_distiller(palette = "YlGnBu",
                                direction = 1,
                                name = "Number of Videos") +
  ggplot2::coord_polar() +
  ggplot2::theme(
    axis.title.x = element_text(size = 22, face = "bold"),
    axis.text.x = element_text(size = 26),
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    legend.text = element_text(size = 18),
    legend.title = element_text(size = 20, face = "bold"),
    legend.box.margin = margin(12, 12, 12, 12)
  )

```
